// <auto-generated />
using System.Reflection;
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624000000_ExpandOrthoClinicalExam")]
    partial class ExpandOrthoClinicalExam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This hand-written migration uses only raw SQL (migrationBuilder.Sql)
            // and its model additions (the Phase 3 structured clinical-exam columns
            // on OrthoClinicalExam) are already present in the current snapshot.
            // Delegate to the snapshot so that EF Core sees no model diff from
            // this migration — same pattern as the other attributed hand-written
            // migrations in this project.
            var buildMethod = typeof(AppDbContextModelSnapshot)
                .GetMethod(
                    "BuildModel",
                    BindingFlags.Instance | BindingFlags.NonPublic);
            buildMethod!.Invoke(
                Activator.CreateInstance<AppDbContextModelSnapshot>(),
                new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
