// <auto-generated />
using System.Reflection;
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621000000_Hotfix_CashFlowCategorySchemaMismatch")]
    partial class Hotfix_CashFlowCategorySchemaMismatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This hand-written migration uses only raw SQL (migrationBuilder.Sql).
            // It does NOT modify the EF Core conceptual model — only the physical
            // database schema (ALTER COLUMN TYPE). Delegate to the current snapshot
            // so that EF Core sees no model diff from this migration.
            var buildMethod = typeof(AppDbContextModelSnapshot)
                .GetMethod(
                    "BuildModel",
                    BindingFlags.Instance | BindingFlags.NonPublic);
            buildMethod!.Invoke(
                Activator.CreateInstance<AppDbContextModelSnapshot>(),
                new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
