// <auto-generated />
using System.Reflection;
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625000000_AddCephNorms")]
    partial class AddCephNorms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This hand-written migration uses only raw SQL (migrationBuilder.Sql)
            // and its model addition (the CephNorm entity / CephNorms table) is
            // already present in the current snapshot. Delegate to the snapshot
            // so that EF Core sees no model diff from this migration — same
            // pattern as the other attributed hand-written migrations in this
            // project.
            var buildMethod = typeof(AppDbContextModelSnapshot)
                .GetMethod(
                    "BuildModel",
                    BindingFlags.Instance | BindingFlags.NonPublic);
            buildMethod!.Invoke(
                Activator.CreateInstance<AppDbContextModelSnapshot>(),
                new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
