// <auto-generated />
using System.Reflection;
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604000000_RemoveLabWorkTypeBranchIdFromSnapshot")]
    partial class RemoveLabWorkTypeBranchIdFromSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This migration contains no schema changes — it exists solely to advance
            // the EF Core migration chain so that the model snapshot is re-evaluated
            // from the current AppDbContextModelSnapshot, which correctly defines
            // LabWorkType without a BranchId property.
            //
            // Delegate to the current snapshot so that EF Core sees no model diff
            // from this migration.
            var buildMethod = typeof(AppDbContextModelSnapshot)
                .GetMethod(
                    "BuildModel",
                    BindingFlags.Instance | BindingFlags.NonPublic);
            buildMethod!.Invoke(
                Activator.CreateInstance<AppDbContextModelSnapshot>(),
                new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
