// <auto-generated />
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711000000_AddFinanceAccountCurrencyAndTreasuryCurrency")]
    partial class AddFinanceAccountCurrencyAndTreasuryCurrency
    {
    }
}
