// <auto-generated />
using System.Reflection;
using AqlanDentalPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AqlanDentalPro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627000000_ExpandOrthoTreatmentPlansP4")]
    partial class ExpandOrthoTreatmentPlansP4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var buildMethod = typeof(AppDbContextModelSnapshot)
                .GetMethod("BuildModel", BindingFlags.Instance | BindingFlags.NonPublic);
            buildMethod!.Invoke(
                Activator.CreateInstance<AppDbContextModelSnapshot>(),
                new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
