using System.Text;
using AqlanDentalPro.API.Services;
using AqlanDentalPro.Domain.Entities;
using AqlanDentalPro.Infrastructure.Services;
using FluentAssertions;
using Xunit;
using LabEntity = AqlanDentalPro.Domain.Entities.Lab;

namespace AqlanDentalPro.UnitTests.Finance;

/// <summary>
/// CLIN-12 regression tests — verify that the async file-I/O + Task.Run refactor of
/// the PDF generators and the new <see cref="PdfLogoCache"/> do not change the
/// generated bytes and that the logo is genuinely cached across calls.
/// </summary>
public class Clin12PdfAsyncIoTests
{
    // ─── PdfLogoCache: cache-once semantics ───────────────────────────────

    [Fact]
    public void PdfLogoCache_TryGetLogo_ReturnsSameReferenceAcrossCalls()
    {
        // First call materializes the Lazy<byte[]?>; subsequent calls must return the
        // exact same byte[] reference — proving the logo is loaded once, not per request.
        PdfLogoCache.TryGetLogo(out var first).Should().BeTrue("a logo.png ships in backend/Fonts");
        PdfLogoCache.TryGetLogo(out var second).Should().BeTrue();

        second.Should().BeSameAs(first,
            "PdfLogoCache must cache the logo bytes statically (CLIN-12) — repeated calls must not re-read the file");
    }

    [Fact]
    public void PdfLogoCache_LogoBytes_IsSameInstanceAsTryGetLogoOutParam()
    {
        PdfLogoCache.TryGetLogo(out var viaOut).Should().BeTrue();
        var viaProperty = PdfLogoCache.LogoBytes;

        viaProperty.Should().BeSameAs(viaOut,
            "LogoBytes property and TryGetLogo out parameter must expose the same cached instance");
    }

    // ─── LabOrderPdfGenerator: async == sync byte-for-byte ───────────────

    [Fact]
    public async Task LabOrderPdfGenerator_GenerateAsync_ReturnsSameBytes_AsSyncGenerate()
    {
        // CLIN-12: GenerateAsync wraps Generate in Task.Run — both paths must produce
        // valid, structurally-equivalent PDFs. We do NOT assert byte-for-byte equality
        // because QuestPDF embeds a document-creation timestamp (and a unique object ID)
        // in the PDF metadata, so two calls separated by even a millisecond differ by a
        // few bytes around index 55 (the CreationDate entry). Asserting exact equality
        // made the test flaky in CI. Instead we verify: (1) both are valid PDFs, (2)
        // both are non-empty, (3) both are approximately the same length (the timestamp
        // delta is < 1% of the file), and (4) the first object header matches.
        var order = CreateSampleLabOrder();
        // CORE-REQ-006: the generator takes the resolved identity rather than three loose
        // strings, so the work order can follow the clinic's print language. Fallback carries
        // the same defaults the three strings used to.
        var identity = FinanceClinicIdentity.Fallback;

        var syncBytes = LabOrderPdfGenerator.Generate(order, identity);
        var asyncBytes = await LabOrderPdfGenerator.GenerateAsync(order, identity);

        asyncBytes.Should().NotBeNullOrEmpty("async path must produce a PDF");
        syncBytes.Should().NotBeNullOrEmpty("sync path must produce a PDF");
        Encoding.ASCII.GetString(asyncBytes, 0, 4).Should().Be("%PDF",
            "async path must produce a valid PDF header");
        Encoding.ASCII.GetString(syncBytes, 0, 4).Should().Be("%PDF",
            "sync path must produce a valid PDF header");
        // Lengths should match within a small tolerance (timestamp/object-id delta only).
        var lengthDelta = Math.Abs(asyncBytes.Length - syncBytes.Length);
        lengthDelta.Should().BeLessOrEqualTo(64,
            "async and sync paths produce structurally equivalent PDFs; only the embedded " +
            "creation timestamp / object id should differ (a few bytes, not the structure)");
    }

    [Fact]
    public async Task LabOrderPdfGenerator_GenerateAsync_ProducesValidPdfHeader()
    {
        var order = CreateSampleLabOrder();

        var bytes = await LabOrderPdfGenerator.GenerateAsync(order, FinanceClinicIdentity.Fallback);

        bytes.Should().NotBeNullOrEmpty();
        Encoding.ASCII.GetString(bytes, 0, 4).Should().Be("%PDF",
            "async PDF generation must still produce a valid PDF (CLIN-12 refactor regression)");
    }

    // ─── Helpers ─────────────────────────────────────────────────────────

    private static LabOrder CreateSampleLabOrder() => new()
    {
        PatientId = Guid.NewGuid(),
        OrderNumber = "LAB-CLIN12-001",
        Status = "sent",
        Priority = "normal",
        ApplianceType = "تاج خزفي",
        SentDate = DateOnly.FromDateTime(DateTime.Today),
        IsActive = true,
        Patient = new Patient
        {
            Id = Guid.NewGuid(),
            FirstName = "محمد",
            LastName = "أحمد",
            PatientNumber = "P-CLIN12",
            IsActive = true,
        },
        Doctor = new Doctor
        {
            Id = Guid.NewGuid(),
            Name = "د. عقلان الكامل",
            IsActive = true,
        },
        Lab = new LabEntity
        {
            Id = Guid.NewGuid(),
            Name = "معمل الأسنان المتقدم",
            Phone = "0509876543",
            IsActive = true,
        },
    };
}
