using System.Text;
using AqlanDentalPro.API.Services;
using AqlanDentalPro.Domain.Entities;
using AqlanDentalPro.Infrastructure.Services;
using FluentAssertions;
using Xunit;
using LabEntity = AqlanDentalPro.Domain.Entities.Lab;

namespace AqlanDentalPro.UnitTests.Finance;

/// <summary>
/// CLIN-12 regression tests — verify that the async file-I/O + Task.Run refactor of
/// the PDF generators and the new <see cref="PdfLogoCache"/> do not change the
/// generated bytes and that the logo is genuinely cached across calls.
/// </summary>
public class Clin12PdfAsyncIoTests
{
    // ─── PdfLogoCache: cache-once semantics ───────────────────────────────

    [Fact]
    public void PdfLogoCache_TryGetLogo_ReturnsSameReferenceAcrossCalls()
    {
        // First call materializes the Lazy<byte[]?>; subsequent calls must return the
        // exact same byte[] reference — proving the logo is loaded once, not per request.
        PdfLogoCache.TryGetLogo(out var first).Should().BeTrue("a logo.png ships in backend/Fonts");
        PdfLogoCache.TryGetLogo(out var second).Should().BeTrue();

        second.Should().BeSameAs(first,
            "PdfLogoCache must cache the logo bytes statically (CLIN-12) — repeated calls must not re-read the file");
    }

    [Fact]
    public void PdfLogoCache_LogoBytes_IsSameInstanceAsTryGetLogoOutParam()
    {
        PdfLogoCache.TryGetLogo(out var viaOut).Should().BeTrue();
        var viaProperty = PdfLogoCache.LogoBytes;

        viaProperty.Should().BeSameAs(viaOut,
            "LogoBytes property and TryGetLogo out parameter must expose the same cached instance");
    }

    // ─── LabOrderPdfGenerator: async == sync byte-for-byte ───────────────

    [Fact]
    public async Task LabOrderPdfGenerator_GenerateAsync_ReturnsSameBytes_AsSyncGenerate()
    {
        // CLIN-12: GenerateAsync wraps Generate in Task.Run — the bytes must be identical
        // so the audit's "don't change the PDF output" rule holds.
        var order = CreateSampleLabOrder();
        var clinicName = "مركز الدكتور عقلان الكامل لتقويم وزراعة وتجميل الأسنان";
        var clinicPhone = "777000000";
        var clinicAddress = "تعز — اليمن";

        var syncBytes = LabOrderPdfGenerator.Generate(order, clinicName, clinicPhone, clinicAddress);
        var asyncBytes = await LabOrderPdfGenerator.GenerateAsync(order, clinicName, clinicPhone, clinicAddress);

        asyncBytes.Should().Equal(syncBytes,
            "async Task.Run wrapper must produce identical bytes to the sync path");
        asyncBytes.Should().NotBeNullOrEmpty();
        Encoding.ASCII.GetString(asyncBytes, 0, 4).Should().Be("%PDF");
    }

    [Fact]
    public async Task LabOrderPdfGenerator_GenerateAsync_ProducesValidPdfHeader()
    {
        var order = CreateSampleLabOrder();

        var bytes = await LabOrderPdfGenerator.GenerateAsync(order, "عيادة الأسنان", "0501234567", "الرياض");

        bytes.Should().NotBeNullOrEmpty();
        Encoding.ASCII.GetString(bytes, 0, 4).Should().Be("%PDF",
            "async PDF generation must still produce a valid PDF (CLIN-12 refactor regression)");
    }

    // ─── Helpers ─────────────────────────────────────────────────────────

    private static LabOrder CreateSampleLabOrder() => new()
    {
        PatientId = Guid.NewGuid(),
        OrderNumber = "LAB-CLIN12-001",
        Status = "sent",
        Priority = "normal",
        ApplianceType = "تاج خزفي",
        SentDate = DateOnly.FromDateTime(DateTime.Today),
        IsActive = true,
        Patient = new Patient
        {
            Id = Guid.NewGuid(),
            FirstName = "محمد",
            LastName = "أحمد",
            PatientNumber = "P-CLIN12",
            IsActive = true,
        },
        Doctor = new Doctor
        {
            Id = Guid.NewGuid(),
            Name = "د. عقلان الكامل",
            IsActive = true,
        },
        Lab = new LabEntity
        {
            Id = Guid.NewGuid(),
            Name = "معمل الأسنان المتقدم",
            Phone = "0509876543",
            IsActive = true,
        },
    };
}
