using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using AqlanDentalPro.Domain.Entities;
using AqlanDentalPro.Infrastructure.Services;
using QRCoder;

namespace AqlanDentalPro.API.Services;

/// <summary>
/// Lab Sprint 5 — Generates PDF for lab orders using QuestPDF.
/// Uses the same Arabic font (Noto Naskh Arabic) registered by PdfService.
/// </summary>
public static class LabOrderPdfGenerator
{
    // Use the same Arabic font as other PDF documents for consistency
    private const string FontName = AqlanDentalPro.Infrastructure.Services.PdfService.ArabicFontName;

    /// <summary>
    /// CORE-REQ-006: takes the resolved identity rather than three loose strings, so this
    /// document can follow the clinic's print language like the finance PDFs do. The caller
    /// already resolved it through FinanceClinicIdentity; it was flattened on the way in.
    /// </summary>
    public static byte[] Generate(LabOrder order, FinanceClinicIdentity identity)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        // Ensure fonts are registered before generating
        AqlanDentalPro.Infrastructure.Services.PdfService.EnsureFontsRegistered();

        var items = order.Items?.OrderBy(i => i.SortOrder).ToList() ?? [];

        var doc = QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1, Unit.Centimetre);
                page.PageColor(Colors.White);
                // Direction follows the print language, as on the finance documents.
                if (!identity.PrintsEnglish)
                    page.ContentFromRightToLeft();
                page.DefaultTextStyle(x => x.FontSize(10).FontFamily(FontName));

                page.Header().Element(compose => ComposeHeader(compose, order, identity));
                page.Content().Element(compose => ComposeContent(compose, order, items, identity));
                page.Footer().Element(compose => ComposeFooter(compose, identity));
            });
        });

        return doc.GeneratePdf();
    }

    /// <summary>
    /// Async wrapper that offloads the CPU-bound QuestPDF <see cref="QuestPDF.Fluent.Document.Create"/>
    /// to the thread pool so the request thread is released while the PDF is composed
    /// (CLIN-12). The generated bytes are identical to <see cref="Generate"/>.
    /// </summary>
    public static Task<byte[]> GenerateAsync(LabOrder order, FinanceClinicIdentity identity) =>
        Task.Run(() => Generate(order, identity));

    private static void ComposeHeader(IContainer container, LabOrder order, FinanceClinicIdentity identity)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(identity.Name).Bold().FontSize(14).FontFamily(FontName);
                    col.Item().Text(identity.Phones).FontSize(9).FontFamily(FontName);
                    col.Item().Text(identity.Location).FontSize(9).FontFamily(FontName);
                });
                row.ConstantItem(130).Element(compose => ComposeTrackingCode(compose, order.OrderNumber ?? order.Id.ToString("N")));
                row.RelativeItem().AlignRight().Column(col =>
                {
                    col.Item().Text(identity.T("أمر عمل معمل", "Lab Work Order")).Bold().FontSize(16).FontFamily(FontName);
                    col.Item().Text($"{identity.T("رقم الطلب", "Order no.")}: {order.OrderNumber}").FontSize(10).FontFamily(FontName);
                    col.Item().Text($"{identity.T("التاريخ", "Date")}: {order.SentDate?.ToString("yyyy-MM-dd") ?? ClinicTimeProvider.ClinicToday().ToString("yyyy-MM-dd")}").FontSize(9).FontFamily(FontName);
                    col.Item().Text($"{identity.T("الأولوية", "Priority")}: {PriorityLabel(order.Priority, identity)}").FontSize(9).FontFamily(FontName);
                });
            });

            column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
        });
    }

    /// <summary>
    /// LABINV-REQ-008 — the scannable tracking code on the lab order slip.
    ///
    /// <para>
    /// <b>What was here before:</b> a decorative strip of bars whose widths came from
    /// <c>value.Aggregate(17, (c, ch) =&gt; c * 31 + ch)</c> — a string hash. It was
    /// labelled "LAB TRACKING", it looked exactly like a barcode, and it encoded nothing.
    /// No reader on earth could decode it. That is worse than printing no code at all:
    /// staff scan it, get nothing, and conclude the scanner is broken rather than that the
    /// barcode is fake.
    /// </para>
    ///
    /// <para>
    /// It is now a real QR code carrying the order number, produced by QRCoder. A phone
    /// camera resolves it, and the lab lookup screen turns it into the order — subject to
    /// the same permissions as every other read.
    /// </para>
    ///
    /// <para>
    /// The order number is printed underneath unchanged. A smudged or torn label must
    /// still be usable by typing, and the human-readable code is what makes that possible.
    /// </para>
    /// </summary>
    /// <summary>
    /// The stored priority is a code ("urgent" / "normal" / "low"). It was printed raw, so an
    /// Arabic work order handed to a Yemeni lab said «الأولوية: normal». Unknown values print
    /// as stored rather than being dropped — a code nobody recognised is still information.
    /// </summary>
    private static string PriorityLabel(string? priority, FinanceClinicIdentity identity) =>
        priority?.ToLowerInvariant() switch
        {
            "urgent" => identity.T("عاجل", "Urgent"),
            "normal" => identity.T("عادي", "Normal"),
            "low"    => identity.T("منخفضة", "Low"),
            _        => priority ?? identity.T("غير محدد", "Not specified"),
        };

    private static void ComposeTrackingCode(IContainer container, string value)
    {
        var qrPng = TryRenderQrPng(value);

        container.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(4).Column(column =>
        {
            column.Item().AlignCenter().Text("LAB TRACKING").FontSize(7).FontColor(Colors.Grey.Darken1);

            if (qrPng is not null)
            {
                column.Item().PaddingVertical(3).AlignCenter().Width(72).Image(qrPng);
            }

            column.Item().AlignCenter().Text(value).FontSize(8).Bold().FontFamily(FontName);
        });
    }

    /// <summary>
    /// Renders the order number as a QR PNG, or null if it cannot be produced.
    /// </summary>
    /// <remarks>
    /// Returning null rather than throwing keeps a QR failure from taking down the whole
    /// work order: the slip is what the lab physically works from, and printing it without
    /// a code is recoverable, while not printing it at all stops the case.
    /// </remarks>
    private static byte[]? TryRenderQrPng(string value)
    {
        try
        {
            using var generator = new QRCodeGenerator();
            // ECC level Q: a lab slip gets handled, taped to a box, and occasionally
            // stained. Q tolerates about 25% damage, which is the realistic condition
            // this label is read in.
            using var data = generator.CreateQrCode(value, QRCodeGenerator.ECCLevel.Q);
            var png = new PngByteQRCode(data);
            return png.GetGraphic(8);
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static void ComposeContent(IContainer container, LabOrder order, List<LabOrderItem> items, FinanceClinicIdentity identity)
    {
        container.Column(column =>
        {
            // Patient & Lab info
            column.Spacing(10);

            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(identity.T("بيانات المريض", "Patient details")).Bold().FontSize(11).FontFamily(FontName);
                    col.Item().Text($"{identity.T("الاسم", "Name")}: {(order.Patient != null ? $"{order.Patient.FirstName} {order.Patient.LastName}" : identity.T("غير محدد", "Not specified"))}").FontFamily(FontName);
                    col.Item().Text($"{identity.T("رقم الملف", "File no.")}: {order.Patient?.PatientNumber ?? identity.T("غير محدد", "Not specified")}").FontFamily(FontName);
                    col.Item().Text($"{identity.T("الطبيب", "Doctor")}: {order.Doctor?.Name ?? identity.T("غير محدد", "Not specified")}").FontFamily(FontName);
                });
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(identity.T("بيانات المعمل", "Lab details")).Bold().FontSize(11).FontFamily(FontName);
                    col.Item().Text($"{identity.T("الاسم", "Name")}: {order.Lab?.Name ?? order.LabName ?? identity.T("غير محدد", "Not specified")}").FontFamily(FontName);
                    col.Item().Text($"{identity.T("الهاتف", "Phone")}: {order.Lab?.Phone ?? identity.T("غير محدد", "Not specified")}").FontFamily(FontName);
                    col.Item().Text($"{identity.T("تاريخ الاستلام المتوقع", "Expected date")}: {order.ExpectedDate?.ToString("yyyy-MM-dd") ?? identity.T("غير محدد", "Not specified")}").FontFamily(FontName);
                });
            });

            // Items table
            if (items.Count > 0)
            {
                column.Spacing(5);
                column.Item().Text(identity.T("بنود العمل", "Work items")).Bold().FontSize(11).FontFamily(FontName);

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(30);  // #
                        columns.RelativeColumn(2);    // Type
                        columns.RelativeColumn(1);    // Tooth
                        columns.RelativeColumn(1);    // Shade
                        columns.RelativeColumn(1);    // Units
                        columns.RelativeColumn(1);    // Price
                        columns.RelativeColumn(1);    // Total
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle).Text("#").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("نوع العمل", "Work type")).FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("السن", "Tooth")).FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("الظل", "Shade")).FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("الوحدات", "Units")).FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("سعر الوحدة", "Unit price")).FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text(identity.T("الإجمالي", "Total")).FontFamily(FontName);
                    });

                    for (var i = 0; i < items.Count; i++)
                    {
                        var item = items[i];
                        table.Cell().Element(CellStyle).Text($"{i + 1}").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.WorkType?.Name ?? identity.T("غير محدد", "Not specified")).FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.ToothNumber ?? identity.T("غير محدد", "Not specified")).FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.Shade ?? identity.T("غير محدد", "Not specified")).FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text($"{item.UnitsCount}").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.UnitPrice.HasValue ? $"{item.UnitPrice:N0}" : "—").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.TotalPrice.HasValue ? $"{item.TotalPrice:N0}" : "—").FontFamily(FontName);
                    }
                });
            }

            // Total
            if (order.TotalCost.HasValue || order.Cost.HasValue)
            {
                column.Spacing(5);
                var total = order.TotalCost ?? order.Cost ?? 0;
                column.Item().AlignRight().Text($"{identity.T("التكلفة الإجمالية", "Total cost")}: {total:N0}").Bold().FontSize(12).FontFamily(FontName);
            }

            // Instructions
            if (!string.IsNullOrWhiteSpace(order.Instructions))
            {
                column.Spacing(5);
                column.Item().Text(identity.T("تعليمات خاصة", "Special instructions")).Bold().FontSize(11).FontFamily(FontName);
                column.Item().Text(order.Instructions).FontSize(9).FontFamily(FontName);
            }

            // Doctor signature
            column.Spacing(20);
            column.Item().Row(row =>
            {
                row.RelativeItem();
                row.ConstantItem(200).Column(col =>
                {
                    col.Item().PaddingBottom(30).LineHorizontal(1).LineColor(Colors.Grey.Darken1);
                    col.Item().AlignCenter().Text(identity.T("توقيع الطبيب", "Doctor signature")).FontSize(9).FontFamily(FontName);
                });
            });
        });
    }

    private static void ComposeFooter(IContainer container, FinanceClinicIdentity identity)
    {
        container.AlignCenter().Text(x =>
        {
            x.Span($"{identity.T("تم إنشاؤه آلياً بواسطة نظام", "Generated automatically by")} {identity.Name}").FontSize(8).FontColor(Colors.Grey.Medium).FontFamily(FontName);
        });
    }

    private static IContainer CellStyle(IContainer container)
    {
        return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(3).PaddingHorizontal(5);
    }
}
