using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using AqlanDentalPro.Domain.Entities;
using AqlanDentalPro.Infrastructure.Services;

namespace AqlanDentalPro.API.Services;

/// <summary>
/// Lab Sprint 5 — Generates PDF for lab orders using QuestPDF.
/// Uses the same Arabic font (Noto Naskh Arabic) registered by PdfService.
/// </summary>
public static class LabOrderPdfGenerator
{
    // Use the same Arabic font as other PDF documents for consistency
    private const string FontName = AqlanDentalPro.Infrastructure.Services.PdfService.ArabicFontName;

    public static byte[] Generate(LabOrder order, string clinicName, string clinicPhone, string clinicAddress)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        // Ensure fonts are registered before generating
        AqlanDentalPro.Infrastructure.Services.PdfService.EnsureFontsRegistered();

        var items = order.Items?.OrderBy(i => i.SortOrder).ToList() ?? [];

        var doc = QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.ContentFromRightToLeft();
                page.DefaultTextStyle(x => x.FontSize(10).FontFamily(FontName));

                page.Header().Element(compose => ComposeHeader(compose, order, clinicName, clinicPhone, clinicAddress));
                page.Content().Element(compose => ComposeContent(compose, order, items));
                page.Footer().Element(compose => ComposeFooter(compose, clinicName));
            });
        });

        return doc.GeneratePdf();
    }

    /// <summary>
    /// Async wrapper that offloads the CPU-bound QuestPDF <see cref="QuestPDF.Fluent.Document.Create"/>
    /// to the thread pool so the request thread is released while the PDF is composed
    /// (CLIN-12). The generated bytes are identical to <see cref="Generate"/>.
    /// </summary>
    public static Task<byte[]> GenerateAsync(LabOrder order, string clinicName, string clinicPhone, string clinicAddress) =>
        Task.Run(() => Generate(order, clinicName, clinicPhone, clinicAddress));

    private static void ComposeHeader(IContainer container, LabOrder order, string clinicName, string clinicPhone, string clinicAddress)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(clinicName).Bold().FontSize(14).FontFamily(FontName);
                    col.Item().Text(clinicPhone).FontSize(9).FontFamily(FontName);
                    col.Item().Text(clinicAddress).FontSize(9).FontFamily(FontName);
                });
                row.ConstantItem(130).Element(compose => ComposeTrackingCode(compose, order.OrderNumber ?? order.Id.ToString("N")));
                row.RelativeItem().AlignRight().Column(col =>
                {
                    col.Item().Text("أمر عمل معمل").Bold().FontSize(16).FontFamily(FontName);
                    col.Item().Text($"رقم الطلب: {order.OrderNumber}").FontSize(10).FontFamily(FontName);
                    col.Item().Text($"التاريخ: {order.SentDate?.ToString("yyyy-MM-dd") ?? ClinicTimeProvider.ClinicToday().ToString("yyyy-MM-dd")}").FontSize(9).FontFamily(FontName);
                    col.Item().Text($"الأولوية: {order.Priority}").FontSize(9).FontFamily(FontName);
                });
            });

            column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
        });
    }

    private static void ComposeTrackingCode(IContainer container, string value)
    {
        var seed = Math.Abs(value.Aggregate(17, (current, ch) => (current * 31) + ch));
        var bars = Enumerable.Range(0, 36)
            .Select(index => ((seed >> (index % 24)) + index) % 3 != 0)
            .ToArray();

        container.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(4).Column(column =>
        {
            column.Item().AlignCenter().Text("LAB TRACKING").FontSize(7).FontColor(Colors.Grey.Darken1);
            column.Item().PaddingVertical(3).Height(28).Row(row =>
            {
                foreach (var isBlack in bars)
                {
                    row.ConstantItem(2).Background(isBlack ? Colors.Black : Colors.White);
                    row.ConstantItem(1).Background(Colors.White);
                }
            });
            column.Item().AlignCenter().Text(value).FontSize(8).Bold().FontFamily(FontName);
        });
    }

    private static void ComposeContent(IContainer container, LabOrder order, List<LabOrderItem> items)
    {
        container.Column(column =>
        {
            // Patient & Lab info
            column.Spacing(10);

            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("بيانات المريض").Bold().FontSize(11).FontFamily(FontName);
                    col.Item().Text($"الاسم: {(order.Patient != null ? $"{order.Patient.FirstName} {order.Patient.LastName}" : "غير محدد")}").FontFamily(FontName);
                    col.Item().Text($"رقم الملف: {order.Patient?.PatientNumber ?? "غير محدد"}").FontFamily(FontName);
                    col.Item().Text($"الطبيب: {order.Doctor?.Name ?? "غير محدد"}").FontFamily(FontName);
                });
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("بيانات المعمل").Bold().FontSize(11).FontFamily(FontName);
                    col.Item().Text($"الاسم: {order.Lab?.Name ?? order.LabName ?? "غير محدد"}").FontFamily(FontName);
                    col.Item().Text($"الهاتف: {order.Lab?.Phone ?? "غير محدد"}").FontFamily(FontName);
                    col.Item().Text($"تاريخ الاستلام المتوقع: {order.ExpectedDate?.ToString("yyyy-MM-dd") ?? "غير محدد"}").FontFamily(FontName);
                });
            });

            // Items table
            if (items.Count > 0)
            {
                column.Spacing(5);
                column.Item().Text("بنود العمل").Bold().FontSize(11).FontFamily(FontName);

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(30);  // #
                        columns.RelativeColumn(2);    // Type
                        columns.RelativeColumn(1);    // Tooth
                        columns.RelativeColumn(1);    // Shade
                        columns.RelativeColumn(1);    // Units
                        columns.RelativeColumn(1);    // Price
                        columns.RelativeColumn(1);    // Total
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle).Text("#").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("نوع العمل").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("السن").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("الظل").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("الوحدات").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("سعر الوحدة").FontFamily(FontName);
                        header.Cell().Element(CellStyle).Text("الإجمالي").FontFamily(FontName);
                    });

                    for (var i = 0; i < items.Count; i++)
                    {
                        var item = items[i];
                        table.Cell().Element(CellStyle).Text($"{i + 1}").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.WorkType?.Name ?? "غير محدد").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.ToothNumber ?? "غير محدد").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.Shade ?? "غير محدد").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text($"{item.UnitsCount}").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.UnitPrice.HasValue ? $"{item.UnitPrice:N0}" : "—").FontFamily(FontName);
                        table.Cell().Element(CellStyle).Text(item.TotalPrice.HasValue ? $"{item.TotalPrice:N0}" : "—").FontFamily(FontName);
                    }
                });
            }

            // Total
            if (order.TotalCost.HasValue || order.Cost.HasValue)
            {
                column.Spacing(5);
                var total = order.TotalCost ?? order.Cost ?? 0;
                column.Item().AlignRight().Text($"التكلفة الإجمالية: {total:N0}").Bold().FontSize(12).FontFamily(FontName);
            }

            // Instructions
            if (!string.IsNullOrWhiteSpace(order.Instructions))
            {
                column.Spacing(5);
                column.Item().Text("تعليمات خاصة").Bold().FontSize(11).FontFamily(FontName);
                column.Item().Text(order.Instructions).FontSize(9).FontFamily(FontName);
            }

            // Doctor signature
            column.Spacing(20);
            column.Item().Row(row =>
            {
                row.RelativeItem();
                row.ConstantItem(200).Column(col =>
                {
                    col.Item().PaddingBottom(30).LineHorizontal(1).LineColor(Colors.Grey.Darken1);
                    col.Item().AlignCenter().Text("توقيع الطبيب").FontSize(9).FontFamily(FontName);
                });
            });
        });
    }

    private static void ComposeFooter(IContainer container, string clinicName)
    {
        container.AlignCenter().Text(x =>
        {
            x.Span($"تم إنشاؤه آلياً بواسطة نظام {clinicName}").FontSize(8).FontColor(Colors.Grey.Medium).FontFamily(FontName);
        });
    }

    private static IContainer CellStyle(IContainer container)
    {
        return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(3).PaddingHorizontal(5);
    }
}
